executor: slurm

restart-times: 0
latency-wait: 60
jobscript: "slurm-jobscript.sh"
cluster-generic-submit-cmd: "slurm-submit.py"
cluster-generic-status-cmd: "slurm-status.py"
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60

use-conda: True
conda-frontend: "conda"

default-resources:
    slurm_partition: "cpu_p"
    slurm_account:   "ife"
    slurm_extra: "'--qos=cpu_normal'"
    mem_mb_per_cpu: 8000
    runtime: "24h"